### ISSUE TITLE
STT Node and audio/ogg

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-red-node-watson#443]
Modify the STT node so that instead of setting 
audio/ogg;codecs=opus
when it detects ogg code it sets
audio/ogg
as the STT service can now automatically detect the codec of the input audio

**Comment by windkh** [comment]
In my opinion the discovery of the file format does not match to the selection of the correct audio format that is sent to the cloud service.

Right now "opus" is detected as file format, but the codec for opus is only added if the file format would be detected as "ogg". Indeed there is an "opus" audio file inside an "ogg" container.

Sounds a little but confusing, but knowing that "ogg" is only a container format for video, audio and other things .... it seems that the call to the cloud service is not correctly parametrized.

**Comment by fmanclossi** [comment]
any news?

**Comment by windkh** [comment]
I have not heard anything from em. Unfortunately. You?

**Comment by chughts** [comment]
It is still on the todo list. This repo is an 'in my own time' project, and I am looking for enough 'own time' in order to go through some of the backlog - this item will be near the top of the priority list for the next batch.

**Comment by chughts** [comment]
Fixed in 0.7.6 awaiting release

**Comment by fmanclossi** [comment]
mmmhh... just updated nodes to 0.7.6 version. Restarted Node-Red, verified that nodes are at 0.7.6 version... but still getting "3/19/2019, 10:00:46 PM
node: b220db42.978fd8
msg : string[66]
"unable to transcode data stream audio/opus -> audio/x-float-array "

curl command correctly transcribes audio file to text.
curl -X POST -u "apikey:---myapikey----" --header "Content-Type: audio/ogg" --data-binary @c:\Users\IBM_ADMIN\Desktop\audio_2019-03-19_09-41-59.ogg  "https://gateway-lon.watsonplatform.net/speech-to-text/api/v1/recognize"

{
   "results": [
      {
         "alternatives": [
            {
               "confidence": 0.88,
               "transcript": "test one two three "
            }
         ],
         "final": true
      }
   ],
   "result_index": 0
}

Any hint?

**Comment by chughts** [comment]
Can you supply a sample .ogg file so I can reproduce the error and maybe figure out what is happening.

**Comment by fmanclossi** [comment]
Hi Soheel, sure. It's the audio message created from my phone using telegram app that I used in the previous message.
Thanks in advance
[audio_2019-03-19_09-41-59.zip](https://github.com/watson-developer-cloud/node-red-node-watson/files/2987456/audio_2019-03-19_09-41-59.zip)

**Comment by chughts** [comment]
The cause is that file-type reports a mime type of 'audio/opus' for the audio file. Consequently the content-type is being set incorrectly. I have a fix 0.7.7 which I will release after I have performed a run int the cloud test.

**Comment by chughts** [comment]
just published 0.7.7

**Comment by fmanclossi** [comment]
Now It works like a charm!!!
Thanks!

**Comment by windkh** [comment]
Cool
